[build]
  publish = "."

# Ensure pretty paths (and any SPA routes) load index.html on refresh
[[redirects]]
  from = "/football/*"
  to = "/index.html"
  status = 200

# Catch-all fallback for other SPA routes if needed
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Always serve fresh copies of sitemap and robots
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "no-store"