[build]
  base = "react-version"
  # Prevent CRA from failing the build on ESLint warnings in CI
  command = "CI= npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Enforce HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Preferred host (redirect www to apex domain if using matchlocator.com)
[[redirects]]
  from = "https://www.matchlocator.com/*"
  to = "https://matchlocator.com/:splat"
  status = 301
  force = true

# Always serve fresh copies of sitemap and robots
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "no-store"

# Noindex sensitive routes
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/api/private/*"
  [headers.values]
    X-Robots-Tag = "noindex"

# Staging contexts: add a global noindex header
[context.deploy-preview]
  [[context.deploy-preview.headers]]
    for = "/*"
    [context.deploy-preview.headers.values]
      X-Robots-Tag = "noindex"

[context.branch-deploy]
  [[context.branch-deploy.headers]]
    for = "/*"
    [context.branch-deploy.headers.values]
      X-Robots-Tag = "noindex"
