[build]
  # Prevent CRA from failing the build on ESLint warnings in CI
  command = "CI= npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Enforce HTTPS for all hosts (including previews)
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Preferred host for production (safe no-op on previews)
[[redirects]]
  from = "https://www.matchlocator.com/*"
  to = "https://matchlocator.com/:splat"
  status = 301
  force = true

# Always serve fresh copies of sitemap and robots
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "no-store"

# Global security headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    # Baseline CSP; adjust if any asset is blocked in console
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self' data: https:; connect-src 'self' https:"

# Noindex for sensitive routes
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/api/private/*"
  [headers.values]
    X-Robots-Tag = "noindex"
