<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>My App</title>
  <script
    defer
    data-domain="matchlocator.com,design.matchlocator.com"
    data-api="https://analytics.kinotto.co/api/event"
    src="https://analytics.kinotto.co/js/script.js"></script>
</head>
<body>
  <div id="root"></div>
</body>
</html>
